-- begin COMMENTINGDATA_COMMENT
alter table COMMENTINGDATA_COMMENT add constraint FK_COMMENTINGDATA_COMMENT_ON_IN_RESPONSE_TO foreign key (IN_RESPONSE_TO_ID) references COMMENTINGDATA_COMMENT(ID)^
alter table COMMENTINGDATA_COMMENT add constraint FK_COMMENTINGDATA_COMMENT_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
alter table COMMENTINGDATA_COMMENT add constraint FK_COMMENTINGDATA_COMMENT_ON_FILE_DESC foreign key (FILE_DESC_ID) references SYS_FILE(ID)^
create index IDX_COMMENTINGDATA_COMMENT_ON_IN_RESPONSE_TO on COMMENTINGDATA_COMMENT (IN_RESPONSE_TO_ID)^
create index IDX_COMMENTINGDATA_COMMENT_ON_USER on COMMENTINGDATA_COMMENT (USER_ID)^
create index IDX_COMMENTINGDATA_COMMENT_ON_FILE_DESC on COMMENTINGDATA_COMMENT (FILE_DESC_ID)^
-- end COMMENTINGDATA_COMMENT
